### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by 5mark** [crushcoder/otr-docker#1]
I installed your script, but when I run it, nothing happens. It would be helpful to get error messages.

**Comment by crushcoder** [comment]
Which script did you run?
The normal docker command under 'Batch' should print out everything to the console, and the different tools and scripts give some error messages.

**Comment by 5mark** [comment]
thanks for your reply. The problem was not related to your docker image, but to my docker daemon not running properly. Your image works excellent, thanks for sharing

**Comment by crushcoder** [comment]
Good to read, thank you.
