### ISSUE TITLE
Works nicely!

### ISSUE THREAD

**Issue by rkrug** [crushcoder/otr-docker#2]
Hi

thanks for this - this was exactly what I was looking for.

I have just one question: Is there a possiblility, that you can include some renaming to the container, so that the files get renamed to the scheme `Titel SxxEyy` so that they can be further processed by e.g. [filebot](https://www.filebot.net/)?

**Comment by crushcoder** [comment]
Hello,

i added a flag. So when you pull the new image and run it set renameFile=true:

`docker run -e "otrEmail=bla@fasel.de" -e "otrPassword=geheim" -e "cutlistAtUrl=http://cutlist.at/user/h52hm126h" -e "renameFile=true" -v ~/Downloads:/otr develcab/otr`

and the name from the cutlist will be used, that should be most often the right name.

**Comment by rkrug** [comment]
Thanks - am trying it out at the moment.

Will let you know if it works.

**Comment by rkrug** [comment]
OK - it works. Is there an option to keep the otr and the uncut files in their intermediate directories, even if the cutting worked? Sometimes the cutting lists are wrong, (as in the 'Tatort_19.06.02_20-15_ard_90_TVOON_DE.avi' where the images are not vcut, but the sound is...) and the actual recording is OK? This would save the re-download (and decoding) of the files?

**Comment by crushcoder** [comment]
You can execute the script "mcall.sh" through adding it to the end of the docker run command.
This will "multicut all" .avi files.
There is also a ffall.sh script which converts everything with ffmpeg.

I also added some "skip" options, see the documentation:
 * (optional) __skipConvert=true__: Only decode and cut, but don't convert to m4v
  * (optional) __skipDecode=true__: No decode, only subsequent steps are executed
  * (optional) __skipCut=true__: Don't cut movie
  * (optional) __skipCleanup=true__: Don't delete intermediate files

**Comment by rkrug** [comment]
Thanks.
