### ISSUE TITLE
BUG: pkill not installed

### ISSUE THREAD

**Issue by rkrug** [crushcoder/otr-docker#5]
Hi

I am getting the following error: does not seem to be serious, as it works, but strange:

```
/otrdecoder-bin-x86_64-unknown-linux-gnu-0.4.1133/multicut.sh: line 901: pkill: command not found
```

likely to be fixed  by installing pkill in line 11 of the docker script?

**Comment by crushcoder** [comment]
multicut tries to kill the mplayer after getting the aspect ratio in this line.
I'm not even sure if this line is executed.
Anyway, i added the package with pkill to the install.
